gitConfig:
  alias.st: status

tasks:
  - name: Setup Environment
    init: |
      bash ./setup.sh
      source /home/gitpod/.bashrc
      fnm install --latest

  - name: Install Dependencies
    init: |
      npm install

  - name: Start Typescript Service
    command: npm run dev
    openMode: tab-after
    env:
      NODE_ENV: development

vscode:
  extensions:
    - jebbs.plantuml
    - redhat.vscode-xml
    - DavidAnson.vscode-markdownlint
    - usernamehw.errorlens
    - Codeium.codeium