const RelationType = {
    Rel_Composition: "Rel_Composition",
    Rel_Composition_Up: "Rel_Composition_Up",
    Rel_Composition_Down: "Rel_Composition_Down",
    Rel_Composition_Left: "Rel_Composition_Left",
    Rel_Composition_Right: "Rel_Composition_Right",
    Rel_Aggregation: "Rel_Aggregation",
    Rel_Aggregation_Up: "Rel_Aggregation_Up",
    Rel_Aggregation_Down: "Rel_Aggregation_Down",
    Rel_Aggregation_Left: "Rel_Aggregation_Left",
    Rel_Aggregation_Right: "Rel_Aggregation_Right",
    Rel_Assignment: "Rel_Assignment",
    Rel_Assignment_Up: "Rel_Assignment_Up",
    Rel_Assignment_Down: "Rel_Assignment_Down",
    Rel_Assignment_Left: "Rel_Assignment_Left",
    Rel_Assignment_Right: "Rel_Assignment_Right",
    Rel_Specialization: "Rel_Specialization",
    Rel_Specialization_Up: "Rel_Specialization_Up",
    Rel_Specialization_Down: "Rel_Specialization_Down",
    Rel_Specialization_Left: "Rel_Specialization_Left",
    Rel_Specialization_Right: "Rel_Specialization_Right",
    Rel_Serving: "Rel_Serving",
    Rel_Serving_Up: "Rel_Serving_Up",
    Rel_Serving_Down: "Rel_Serving_Down",
    Rel_Serving_Left: "Rel_Serving_Left",
    Rel_Serving_Right: "Rel_Serving_Right",
    Rel_Association: "Rel_Association",
    Rel_Association_Up: "Rel_Association_Up",
    Rel_Association_Down: "Rel_Association_Down",
    Rel_Association_Left: "Rel_Association_Left",
    Rel_Association_Right: "Rel_Association_Right",
    Rel_Association_dir: "Rel_Association_dir",
    Rel_Association_dir_Up: "Rel_Association_dir_Up",
    Rel_Association_dir_Down: "Rel_Association_dir_Down",
    Rel_Association_dir_Left: "Rel_Association_dir_Left",
    Rel_Association_dir_Right: "Rel_Association_dir_Right",
    Rel_Flow: "Rel_Flow",
    Rel_Flow_Up: "Rel_Flow_Up",
    Rel_Flow_Down: "Rel_Flow_Down",
    Rel_Flow_Left: "Rel_Flow_Left",
    Rel_Flow_Right: "Rel_Flow_Right",
    Rel_Realization: "Rel_Realization",
    Rel_Realization_Up: "Rel_Realization_Up",
    Rel_Realization_Down: "Rel_Realization_Down",
    Rel_Realization_Left: "Rel_Realization_Left",
    Rel_Realization_Right: "Rel_Realization_Right",
    Rel_Triggering: "Rel_Triggering",
    Rel_Triggering_Up: "Rel_Triggering_Up",
    Rel_Triggering_Down: "Rel_Triggering_Down",
    Rel_Triggering_Left: "Rel_Triggering_Left",
    Rel_Triggering_Right: "Rel_Triggering_Right",
    Rel_Access: "Rel_Access",
    Rel_Access_Up: "Rel_Access_Up",
    Rel_Access_Down: "Rel_Access_Down",
    Rel_Access_Left: "Rel_Access_Left",
    Rel_Access_Right: "Rel_Access_Right",
    Rel_Access_r: "Rel_Access_r",
    Rel_Access_r_Up: "Rel_Access_r_Up",
    Rel_Access_r_Down: "Rel_Access_r_Down",
    Rel_Access_r_Left: "Rel_Access_r_Left",
    Rel_Access_r_Right: "Rel_Access_r_Right",
    Rel_Access_rw: "Rel_Access_rw",
    Rel_Access_rw_Up: "Rel_Access_rw_Up",
    Rel_Access_rw_Down: "Rel_Access_rw_Down",
    Rel_Access_rw_Left: "Rel_Access_rw_Left",
    Rel_Access_rw_Right: "Rel_Access_rw_Right",
    Rel_Access_w: "Rel_Access_w",
    Rel_Access_w_Up: "Rel_Access_w_Up",
    Rel_Access_w_Down: "Rel_Access_w_Down",
    Rel_Access_w_Left: "Rel_Access_w_Left",
    Rel_Access_w_Right: "Rel_Access_w_Right",
    Rel_Influence: "Rel_Influence",
    Rel_Influence_Up: "Rel_Influence_Up",
    Rel_Influence_Down: "Rel_Influence_Down",
    Rel_Influence_Left: "Rel_Influence_Left",
    Rel_Influence_Right: "Rel_Influence_Right",
}

type RelationTypeKey = keyof typeof RelationType;
type RelationTypeValue = typeof RelationType[RelationTypeKey];

function Relation(type: RelationTypeValue, from: string, to: string, label: string): string {
  return `${type}("${from}", "${to}","${label}")`;
}

Relation.type = RelationType;

export { Relation };
